### PR TITLE
Added open terminal option

### PR DESCRIPTION
**Pull request by saksham4106**
Before merging it would be great   if mac and linux users if any could test if it works for them

### CODE REVIEW

**Comment by BHLoneWolf0** [comment]
i can by vm right?

**Comment by saksham4106** [comment]
yea it should be the same

**Comment by BHLoneWolf0** [comment]
> yea it should be the same
alr then gonna try it now

**Comment by saksham4106** [comment]
The open terminal thingy is in the view tab

**Comment by BHLoneWolf0** [comment]
didn't work cause my ubuntu is shit

**Comment by DaRealTurtyWurty** [comment]
Ok I won't pull until we have more confirmation that it works on different OS.

**Comment by DaRealTurtyWurty** [comment]
Also there's a gitignore conflict

**Comment by saksham4106** [comment]
the gitignore was because i am stupid and the metadata of my workspace was in the project so i first added it to gitignore
then edited the file to remove that

**Comment by Affehund** [comment]
Btw why do you have an extra class for the OS checking? We already have something like this in the Utils class.

https://github.com/saksham4106/Modding-IDE/blob/master/src/main/java/io/github/railroad/utility/GetOS.java
->
https://github.com/Railroad-Team/Modding-IDE/blob/master/src/main/java/io/github/railroad/utility/Utils.java

**Comment by Sparky200** [comment]
> We already have something like this in the Utils class.

Not for long

**Comment by saksham4106** [comment]
I tested it on linux and it works 
dunno about mac i guess it should be ok

**Comment by saksham4106** [comment]
commited fabric mod helper thingy

**Pull request merged**
