### PR TITLE
Added JavaFX as a Gradle dependency

### PR DESCRIPTION
**Pull request by TheOnlyTails**
To run the project, use the `gradlew run` command, or use a Gradle run configuration).
This makes setting up the project much simpler, since you don't need to do anything.
It also adds compatibility with Java 15.

Added Gradle CI.

Added a Hebrew translation.

Did some simple refactoring (nothing major).

### CODE REVIEW

**Comment by TheOnlyTails** [comment]
I deleted my whole project folder, just to see how easy it is to set up the repo now, and here are the instructions from opening the project to running:
Clone the repo
Load the Gradle project
Run `gradlew run`

That's it.

**Comment by DaRealTurtyWurty** [comment]
Still waiting for confirmation from other people that this doesn't just break everything in existence as it did for me. Also, the conflicts need resolving.

**Comment by TheOnlyTails** [comment]
I found out why it was not working: you needed to change the Gradle JVM here: 
image

If you set it to something above 8, it will work. On that note, why are we even using Java 8?

**Comment by TheOnlyTails** [comment]
On other note, I'm closing this PR and making a new one with the new folder structure.

**Pull request closed without merging**
