### PR TITLE
Project Creation, New File>New Menu

### PR DESCRIPTION
**Pull request by Cy4Shot**
yes, another one, ill stop spamming once i get github to work/
no, this isnt actually 31 commits, its 10 ish.

## What is in this PR?
 - A temporary banner for the website
 - The final File>New menu we decided on in #brainstorm
 - Forge Version Helper which allows you to get all kinds of information about forge versions.
 - The Project creation dialog

### CODE REVIEW

**Review by jojo2357 — COMMENTED** [review]
Not sure whats going in in RailroadTopMenu so I wont approve. Besides its probably all getting chunked anyway

**Comment by Cy4Shot** [comment]
> Not sure whats going in in RailroadTopMenu so I wont approve. Besides its probably all getting chunked anyway

yeah, we discussed this with steven and some others on discord. should be the most intuitive layout we can make.

**Comment by PutoPug** [comment]
w8 what is the diff between rebase & merge

**Comment by jojo2357** [comment]
https://www.atlassian.com/git/tutorials/merging-vs-rebasing

Basically when you pr and your commits get squashed into one, it registers that you have commits (the ones just merged) that arent on upstream/master so a merge just adds them all together but rebase will look at upstream and based on the changes after where your fork branches off, either apply your extra commits or disregard them

**Comment by Cy4Shot** [comment]
so, can we merge this?

**Comment by Cy4Shot** [comment]
ok, i fixed some of the bad code, this should be a lot better now

**Comment by Cy4Shot** [comment]
can some1 review this?

**Review by PutoPug — APPROVED** [review]
Works, Stable

**Review by saksham4106 — APPROVED** [review]
Looks Good to me

**Pull request closed without merging**
